name: PopolSurvival
author: Nathan Fallet
main: me.nathanfallet.popolsurvival.PopolSurvival
depend: [PopolServer]
load: STARTUP
version: 1.0
api-version: 1.16
commands:
    chunk:
        description: Gérer les chunks
        aliases: [c]
    feed:
        description: Regénre la barre de nourriture
    fly:
        description: Active ou désactive le fly
    team:
        description: Gérer sa team de survie
        aliases: [t]
    job:
        description: Gérer son métier
    setrandomtp:
        description: Definir le point de random tp
        permission: popolsurvival.setrandomtp
    bed:
        description: Se téléporter à son lit
